### ISSUE TITLE
[ENHANCEMENT] PMA-Voice Cycle Proximity - 

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#1]
**What feature you want to improve**
PMA-Voice Cycle Proximity 

**How could this feature be improved? Please describe your idea as much as possible**

Currently how its setup!

whisper -  is little more than half voice

Normal - Full Voice

Shouting Full voice

****How to improve****

Whispering - should be able 1/4 of full

Normal - Should be half full

Shouting - should be Full voice

**Comment by ixhal** [comment]
This bug has been fixed and will be live on the next server restart! Thanks for the report buddy
