### ISSUE TITLE
ICU issues

### ISSUE THREAD

**Issue by BIRLZ95** [Reprieve-RP/feedback#10]
When checking yourself into ICU you can see/merge through the wall when u leaving.

You can also use items with in the ICU and drop/pick them up. For example I can use drugs while being laid in the ICU.

![image](https://user-images.githubusercontent.com/64453673/189531346-9bfa03be-cafe-4b4c-afb5-242881cc18b0.png)

**Comment by ixhal** [comment]
Oi oi take some fatty coke while laid in bed!
Will look into it cheers bro

**Comment by BIRLZ95** [comment]
You can use your gun while laid in the ICU, shoot etc, your also unable to exit/move once you do that, I had to noclip to fix.
