### ISSUE TITLE
Chicken Job 

### ISSUE THREAD

**Issue by BIRLZ95** [Reprieve-RP/feedback#14]
Chicken job doesnt last long enough,

Catch three chickens>process>sell

You should have the ability to catch alot more chickens to extend the job.

**Comment by ixhal** [comment]
You can continue to enter the pen after you catch the first 3 but will extend it to 5 since you can carry a max of 10!

**Comment by BIRLZ95** [comment]
Yh I realised this after lol, thanks though!
