### ISSUE TITLE
Parachute Clothing Item Issue

### ISSUE THREAD

**Issue by BIRLZ95** [Reprieve-RP/feedback#15]
See picture for example.

Select/Deselect parachutes unlimited times potentionally causing server issues, I suggest making it a item instead or something.
 
![image](https://user-images.githubusercontent.com/64453673/191265326-00f23cab-0192-49b0-8e01-9c2a5bcabd2b.png)

**Comment by ixhal** [comment]
Sorted this when I added the blacklist/whitelist feature earlier
