### ISSUE TITLE
[ENHANCEMENT] 24/7 Store Stock - Public Opinion Needed

### ISSUE THREAD

**Issue by TheAlphaStrain** [Reprieve-RP/feedback#16]
**What feature you want to improve**
(Fishing/Hunting/Bank Robberys/ ect)
So this is more so of a public opinion we need about Store Stock. I, personally, am fine with it either way. So, as it currently sits, you may or may not know that the 24/7 Stores have limited stock. (At the time of writing this, for testing Uber Eats it's been changed from 50 to 500 of each item.) So over time, yes, the stock will become zero. How does the store restock you ask? Well, via the Trucker Job. Each time you make a delivery doing the Trucker Job you restock the stores. Should you complete the entire route, it'll take you to every store including Rob's Liquor. 

**How could this feature be improved? Please describe your idea as much as possible**
Here's where public opinion would be greatly appreciated as I and another member of staff are at odds with whether or not this is a good system to have. 

My opinion: I'd like to see the community rise to the challenge to want to make it in the steps of player driven economy such as doing the trucker job to restock the shelves. I feel like if you, the players, know that's something that needs to be done it might not be so bad. But, I won't be disappointed if that's not the popular public opinion.

The opposing opinion (Directly from them): Doing this would force people in the city to do a public job to stock the stores for the city and take time away from what you, as a player, want to do and how you want to RP. This may anger some people because they're not doing what they want at any given time.

**Additional information**
Your thoughts would be greatly appreciated.

**Comment by ixhal** [comment]
Going to close this since no one else replied and I have not personally heard of any issues with the current system, If it becomes more of a issue is the future we can revisit this.
