### ISSUE TITLE
[ENHANCEMENT] Garbage job

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#2]
**What feature you want to improve**
Garbage job

**How could this feature be improved? Please describe your idea as much as possible**

No bag showing in your hand when you have picked up a bag.  Only way to tell you have a bag is from the text that shows up, be nice to see the bags in hand.

**Comment by MintPoloo** [comment]
Props need adding for this job, it is on the to do list to complete. Thanks for the feedback though Troopa!

**Comment by ixhal** [comment]
Props have been added to the anti-cheat exceptions!
Thanks!!
