### ISSUE TITLE
Car Repo - Email Content

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#21]
on the car repossession job the email you get contains some % strings instead of the desired car license plate / model

![car repo vehichle](https://user-images.githubusercontent.com/121685463/210093615-abbf01dc-6302-4876-ab9c-f2996058979e.png)

**Comment by ixhal** [comment]
I have messaged the dev about this issue but he is away for the holidays, all we can do at the moment is wait :(

**Comment by MintPoloo** [comment]
This should now be fixed! As soon as Alan gets up I'll get him to push the update! Thank you for the feedback!
