### ISSUE TITLE
Garbage Job - Messages

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#22]
For the prompts on the garbage job instead of bags it could be bag(s) so the prompt makes grammatical sense for whatever amount you're on.

![garbage](https://user-images.githubusercontent.com/121685463/210093690-7ec2c906-656e-4b8d-9fd2-d9c5a830372b.png)

**Comment by ixhal** [comment]
I have changed it to your suggestion, Thanks!
