### ISSUE TITLE
Car Repo - Letter not removed on cancelled job.

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#23]
If you cancel on a job the car repo letter isn't removed from inventory like it is when you complete.

**Comment by ixhal** [comment]
Unfortunately this script was purchased from someone so I cant edit it my self but i will contact the dev about it! Cheers

**Comment by MintPoloo** [comment]
This should now be fixed! As soon as Alan gets up I'll get him to push the update! Thank you for the feedback!
