### ISSUE TITLE
Car Wash - String Grammar 

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#24]
In the car wash the string displays "Washing Car" this would make more sense to be "Wash Car" or "Clean Car" or something similar.

![car wash](https://user-images.githubusercontent.com/121685463/210107404-bb882f92-d05f-4f13-b76a-fbf4b188d231.png)

**Comment by ixhal** [comment]
I got to change this system anyway to the better more realistic one I made a while ago, Thanks for reminding me!

**Comment by ixhal** [comment]
System has been changed, Thanks for the feedback!
