### ISSUE TITLE
Motorcycle - X to kick

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#25]
On Motorbikes currently the "kick" function isn't fully operational - pressing X to kick on the bike also puts your hands up which stops you from steering.

**Comment by ixhal** [comment]
I am unsure if we will keep it like this or not, Maybe a poll is in order for this one!

**Comment by ixhal** [comment]
It was decided by the community to disable this feature so it has now been disabled! Thanks for the feedback
