### ISSUE TITLE
[ENHANCEMENT] CarJacking Horn

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#26]
**What feature you want to improve**
Car Jacking Horn

**How could this feature be improved? Please describe your idea as much as possible**
When stealing a car with a lockpick we could have the horn that continuously beeps for a period of time.

**Comment by ixhal** [comment]
Im going to poll this and leave it up to the community to decide! Thanks for the suggestion

**Comment by ixhal** [comment]
This has been added to the server! Thanks for the suggestion!
