### ISSUE TITLE
Pawn Shop - Prices 

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#29]
Currently in the Pawn Shop you can sell general consumables like water/food and the prices to sell are higher than you can buy them for in the store.

e.g 
Water Bottle in the corner store to buy = $2
Water Bottle in the pawn shop to sell = $10

**FREE MONEY**

![image_2023-01-02_194454664](https://user-images.githubusercontent.com/121685463/210272971-91536ce3-8925-4f45-9fb2-a73461d038b2.png)

**Comment by ixhal** [comment]
Thank you for the report, I have removed all the items that can be abused!
