### ISSUE TITLE
Car Jacking - Stuck

### ISSUE THREAD

**Issue by reeceCC** [Reprieve-RP/feedback#31]
Over the past couple days me and soup have both had the same issue, i'm not sure what's actually causing it but at some point while carjacking it can glitch and basically messes you up.

You get stuck and can't do stuff like putting your hands up or jump or sprint properly and the only way to fix it is by flying out.

I'll try grab a video of it happening so I can post it here.

**Comment by ixhal** [comment]
issue should be fixed now, Thanks!
