### ISSUE TITLE
Boosting Cars - Pricing Balance 

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#32]
**What is the issue involving?**
Boosting Cars

crypto pricing needs to come down. I just did a boost for a Washington an made 40k

**In your opinion what is the way to fix this?**

Either crypto pricing needs to come way down or the amount of crypto you receive from doing boosts needs to be cut way down.

**Comment by ixhal** [comment]
Should be balanaced enough for launch now, Will keep a eye on it thank you!
