### ISSUE TITLE
Boat Pricing

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#34]
**What is the issue involving?**
All Boats are currently the same price

**In your opinion what is the way to fix this?**
this should be tiered to different prices. 

![image](https://user-images.githubusercontent.com/89701754/210628116-56e6b3ec-4827-42da-bb63-5b75dfe6bb34.png)

**Comment by ixhal** [comment]
Shaggy has kindly gone through and changed all the boat prices so this issue is now solved, Thank you!
