### ISSUE TITLE
House Decor TV

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#35]
**What is the issue involving?**
House Decor TV

**In your opinion what is the way to fix this?**

This style TV doesn't allow you to play anything on it, not sure if its suppose to or not but would be nice. 

![image](https://user-images.githubusercontent.com/89701754/210628364-73e5fc37-9f04-487f-adb3-c27d4a92b88b.png)

**Comment by ixhal** [comment]
I need the name of the option in the menu where you got this please

**Comment by troopakoopa** [comment]
its this one sorry about that

![image](https://user-images.githubusercontent.com/89701754/211128124-5715df03-1cab-49b9-a920-9bec2f65afde.png)

**Comment by ixhal** [comment]
Thanks! Issue will be sorted after the next restart :)
