### ISSUE TITLE
Larry's Used Auto - Add Circle 

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#39]
**What feature you want to improve**
Larry's used auto lot,

**How could this feature be improved? Please describe your idea as much as possible**
Add a Circle to the ground on the side of the building so people know where to go to sell their cars 

![image](https://user-images.githubusercontent.com/89701754/210628877-7caa7c1d-568c-4b13-8b95-55af31f45b5b.png)

**Additional information**

**Comment by ixhal** [comment]
Added a marker there thank you!
