### ISSUE TITLE
[ENHANCEMENT] Checking into hospital

### ISSUE THREAD

**Issue by MintPoloo** [Reprieve-RP/feedback#4]
**What feature you want to improve**

Checking in

**How could this feature be improved? Please describe your idea as much as possible**

Currently when you check into the hospital you can walk straight out with 0 cooldown.

Also it currently charges you when checking into the hospital:

$2,000 first stage down
$5,000-$10,000 second stage down

**Comment by ixhal** [comment]
Change to 150 bucks each time you check in + 2 minutes of time spent in beds before you are allowed up.
- TODO -
Fix coords to put in actual beds in pillbox
Add all areas to sandy shores medical.

**Comment by ixhal** [comment]
All this has been sorted now! Thank ya
