### ISSUE TITLE
PD Invoice system

### ISSUE THREAD

**Issue by JakeWalker1** [Reprieve-RP/feedback#45]
**What feature you want to improve**
PD Invoice system

**How could this feature be improved? Please describe your idea as much as possible**
When invoicing people they are able to deny or accept the invoice, this needs to be changed to they don't have that option and the invoice comes out of the bank straight away

**Additional information**
![image](https://user-images.githubusercontent.com/66036202/210630064-b6c09c38-8774-43dd-8f27-7231e88547c8.png)
![image1](https://user-images.githubusercontent.com/66036202/210630066-151aed04-be12-432a-9af7-61f04455a177.png)

**Comment by ixhal** [comment]
Added a /fine command for this now.
