### ISSUE TITLE
[ENHANCEMENT] Hunting

### ISSUE THREAD

**Issue by MintPoloo** [Reprieve-RP/feedback#5]
**What feature you want to improve**

Killing animals

**How could this feature be improved? Please describe your idea as much as possible**

At the moment, when you shoot any animal with the hunting rifle they keep getting back up and running away

**Comment by troopakoopa** [comment]
Also hunting License an lodge location not shown on map.

**Comment by ixhal** [comment]
Blip has been added!
Fixed the issue for not being able to kill them with the hunting rifle also.
hunting is pretty much complete just needs testing!
