### ISSUE TITLE
Contract DLC vehicles with armour plating

### ISSUE THREAD

**Issue by JakeWalker1** [Reprieve-RP/feedback#50]
All the vehicles in the contract DLC have an option to add armour plating to the vehicles at the mechanics

The buffalo STX for example this has armour playing on the doors, this makes the car a lot stronger than normal
![image](https://user-images.githubusercontent.com/66036202/210638459-5102f821-d912-4479-ac6b-c1986374e502.png)

Is this something we want to keep or something that would want changing?

**Comment by MintPoloo** [comment]
This car has bullet proof windows from default

**Comment by MintPoloo** [comment]
Buffalo STX
Dewbauchee Champion
Enus Deity
Enus Jubilee

These cars all come with default bullet proof windows and armour plates can be added

**Comment by ixhal** [comment]
These vehicles have been removed from the shop for now
