### ISSUE TITLE
[BALANCE] D8 wages imbalanced

### ISSUE THREAD

**Issue by llanboy** [Reprieve-RP/feedback#51]
**What is the issue involving?**
CEO and management level earn the same $270 per pay cheque

**In your opinion what is the way to fix this?**
Make the CEO position paid more as I believe this is the case with other jobs (sorry if I'm wrong but I would of thought it would be higher pay)

Thank you

**Comment by TheAlphaStrain** [comment]
Can't speak for other departments, as my brief moment as deputy chief for EMS, I got paid the same as the Chief after pay structure was implemented. Then it trickles down from there.

**Comment by llanboy** [comment]
As long as it is consistent that's fine I was just worried it was a mistake as you would expect the highest rank to be on the most

**Comment by ixhal** [comment]
This issue was you was missing a CEO rank
