### ISSUE TITLE
[ENHANCEMENT] Pumping Gas Not working

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#6]
**What feature you want to improve**
Not sure if it is the vehicle I was using the Tron bike from PDM or if it is a bug. When I went to gas stations to fill up it would tell me that the bike was full already, but the bike gas tank was in the red an beeping at me. 

I tested with no cash in pockets an also with cash in pockets, same results. 

**How could this feature be improved? Please describe your idea as much as possible**

**Additional information**

**Comment by MintPoloo** [comment]
Thank you Troppa, we will look into this.

**Comment by ixhal** [comment]
Sorted it, Changed something a while ago to stop the vehicle from spluttering at low fuel (doing some stupid reverse mechanic) and forgot to change something while in there, Should be all good on the next reboot
