### ISSUE TITLE
Removing illegal items at Pill-Box

### ISSUE THREAD

**Issue by troopakoopa** [Reprieve-RP/feedback#60]
**What feature you want to improve**
Removing illegal items when going to pillbox from /respawn or checked in, currently legal pistols have been removed an disabler. All Drugs, knifes, burner phone were left in inventory.

**How could this feature be improved? Please describe your idea as much as possible**

I suggest legal pistols, knifes and bullets be kept since we have weapon license an remove all drugs, illegal knifes and guns, boosting  laptop, disabler, burner phone all be removed when going to pillbox from /respawn or checking in. 

![image](https://user-images.githubusercontent.com/89701754/211127812-48e7daf9-05c3-425e-8c6d-2f028914c724.png)

![image](https://user-images.githubusercontent.com/89701754/211127905-1c99d4f6-0f7a-4461-b38c-376ff27c06a7.png)

**Comment by CowboyNation7474** [comment]
It removes PD weapons when respawning

**Comment by ixhal** [comment]
This should no longer be a issue as I changed the system for removing items on taking local respawn a while back
