### ISSUE TITLE
Injuries

### ISSUE THREAD

**Issue by JakeWalker1** [Reprieve-RP/feedback#67]
**What feature you want to improve**
Injuries 

**How could this feature be improved? Please describe your idea as much as possible**
When you get hit by a car you notice your leg hurts etc this makes you fall over constantly until you die
every 0.5 seconds you fall over, this needs to be reduced or something 
**Additional information**

**Comment by troopakoopa** [comment]
I had this happen to me as well, had to call EMS, but it is impossible to move when you hurt you leg. maybe adding some type of splint to hardware stores to buy or craft this was you can at least drive to hospital or wait on EMS. having splint only last like 5 mins

**Comment by ixhal** [comment]
I think you guys are missing the point that its for medic RP and that you should take care of your self and not run into vehicles or jump off buildings, By adding a splint to the store it takes away a lot of medical RP and I don't think that is the right move at all, Just call EMS and take care of your self.

**Comment by MegFlurries** [comment]
With leg injuries you wouldn't be able to walk so falling over constantly is better than not being able to walk. EMS is to call wait for them if walking and falling gets too overstimulating.

**Comment by troopakoopa** [comment]
I 100% behind making sure Medics have RP an i do agree. but when you are playing an there is no medics on nor PD on there is nothing that can be done. 

Why i suggested that we have some type of Leg splint that lasts 5-10 mins max then the leg injuries start happening again so you can at least get to Pill Box to check yourself in when there is no medics on.

**Comment by JakeWalker1** [comment]
It's nothing about the med rp I want all the med rp I can get, it's getting hit by a local car going 4 mph and my leg is completely fucked, getting nudged by a car makes u fall over every .5 seconds if I got hit going like 10 15 MPH fair enough but it was the slow speed high damage I'm talking about.

**Comment by JakeWalker1** [comment]
I know for a fact injuries can tweaked and be reduced for how often you fall over, how much damage you need to take to the leg to fall over how fast you bleed out etc, if nothing can be done then it's no biggie :) just slightly annoying to deal with

**Comment by ixhal** [comment]
I changed the chances of ragdoll happening as well as added a 10-25 second timer after falling over before you can fall over again to make this less frustrating for people. I had caught someone and they got hit by a vehicle and started to ragdoll but using bandages seemed to help them or at least it made them stable enough to walk. Hopefully it makes the system a bit less frustrating but in general these systems are always frustrating to most people. I just hope it makes it a bit more tolerable. Will keep a eye on it in the future but don't want to kill med RP.
