### ISSUE TITLE
[ENHANCEMENT] Police Sirens

### ISSUE THREAD

**Issue by HelloCrash** [Reprieve-RP/feedback#69]
**What feature you want to improve**
Police Sirens

**How could this feature be improved? Please describe your idea as much as possible**
We found out that the police sirens will be audible from about 2-3 miles away while only running the lights without sirens.
I had the hunch calls come in a little late because I was 0.10miles away from a car jacking twice and no one to be found in the area.

I now think they might be alerted way beforehand due to us just running lights without sirens and the result being them hearing sirens very clearly.

**Additional information**
I don't have a clear fix for this issue but I want it to be known.

Thank you for your efforts!

**Comment by ixhal** [comment]
Closing this issue due to it being the same as #70 :)
