### ISSUE TITLE
[ENHANCEMENT] Luxury Vehicle Shop

### ISSUE THREAD

**Issue by MintPoloo** [Reprieve-RP/feedback#7]
**What feature you want to improve**

You can not get inside

**How could this feature be improved? Please describe your idea as much as possible**

There is a blip for this on the map and you can see the cars through the window, however you can no go through the doors. Also super and high end cars are not obtainable at PDM.

**Comment by ixhal** [comment]
Removed this MLO a while ago and forgot to add it back, Should be fixed next restart!
