### ISSUE TITLE
[BUG REPORT] Extremely Cheap Gas

### ISSUE THREAD

**Issue by TheAlphaStrain** [Reprieve-RP/feedback#71]
I noticed if you have like say $10 cash on you, you go to the gas to station to fill up your car, it will fill a little bit, but soon as the price reaches past the amount in your wallet it will just stop. Then you can press it again and it'll do it again. Up until the last time you need to press it to fill your car, it'll take what it used to fill it from that point. For example, I did this like 4 times and on the 4th time it only took $7 of the $10 I had in my wallet but I filled my vehicle from 50% to full.

**Comment by ixhal** [comment]
This issue should now be fixed, Thanks! :)
