### ISSUE TITLE
House robberies possibly not working?

### ISSUE THREAD

**Issue by JakeWalker1** [Reprieve-RP/feedback#72]
**What is the issue involving?**
House Robberies

**In your opinion what is the way to fix this?**
Might not need fixing but i have a feeling house robberies dont work, im 99% sure i have the stuff for it, there is cops around and its night time etc, theres no prompt or anything when trying to attempt the robbery

**Additional information**

**Comment by ixhal** [comment]
They are working fine on dev all you need is a advanced lockpick and use it near a door

**Comment by TheAlphaStrain** [comment]
To further ixhal's point, sometimes what you might think is the "right door" may not be. So, just a matter of finding the right door as well. Most of them should be obvious though.

**Comment by JakeWalker1** [comment]
I tried all the grove houses, most houses in the hills, and 5-6 in mirror park, i tried houses ive tried in other cities that u were able to rob, but ill try again
