### ISSUE TITLE
Robs Liquor Safes

### ISSUE THREAD

**Issue by Ali-Walker** [Reprieve-RP/feedback#73]
Either the robs liquor safe doesnt work we need like pop ups to actually tell us what to do, its similar to what ive seen before but makes 0 sense, me and jake both sat there through 6-7 clicks and still nothing

**Comment by troopakoopa** [comment]
I can confirm these work.

**Comment by Ali-Walker** [comment]
okay i can confirm they work but you get jack shit from them, i got 1 276 bag and thats it

**Comment by ixhal** [comment]
You got unlucky it happens $276 for 2 seconds work with minimal risk is nothing to be laughed at considering you can get 3 bags and the max they can have in them is 500.
