### ISSUE TITLE
[BUG REPORT] Burger Shot

### ISSUE THREAD

**Issue by TheAlphaStrain** [Reprieve-RP/feedback#77]
If you clock in as a cashier, if you, presumably, don't have a customer to server an order to but you're going through the motions of putting an order together, you get the "Green dot" that says "Click on the customer to confirm order or backspace to cancel" or something. If you go to cancel it you're stuck in an endless loop of looking like you're pressing buttons on the cash register.

**Comment by ixhal** [comment]
Issue should be fixed on the next server restart
