### ISSUE TITLE
[FEATURE] Boat Fuel

### ISSUE THREAD

**Issue by TheAlphaStrain** [Reprieve-RP/feedback#79]
**Describe in as much detail as possible for the feature you are requesting.**
Pretty simple, need a way to fill up the boat with gas. Even storying it in your garage doesn't fill it up.

**In what ways would this improve the in-game experience?**
Well, you can't do all aspects of fishing without a boat, without being able to refill the boat with gas it'll just end up being a big paper weight eventually lol.

**Will this require work in other parts of the game? Example: (Inventory/Jobs)**
No, I figure we already have Jerry Cans, why not that be the way it works? Or make them auto refill when you store them. Idk lol.

**Comment by ixhal** [comment]
Boat refilling stations will be added on the next restart, Thanks for the report :)
