### ISSUE TITLE
[ENHANCEMENT] Mining - Washing

### ISSUE THREAD

**Issue by TheAlphaStrain** [Reprieve-RP/feedback#8]
**What feature you want to improve**
Mining - Specifically washing

**How could this feature be improved? Please describe your idea as much as possible**
As it currently sits, you get 5 rocks per "mine". That's awesome. I did the entire mine and got about 70 rocks. The problem is, when you go to wash them... you're washing 1 rock at a time. Meaning you gotta sit there, do all the motions to wash the rock one... at... a... time. Sitting here falling asleep like "Should almost be done right? I get 5 rocks per so I think I'm washing 5 per." yyyeah... nope. Ain't even done 20 yet.

**Additional information**
Just did the calculations. You're looking at about 15 seconds per rock. 4 per minute. You're looking at about 17.5 minutes to wash it all. That's quite a long time in my opinion.

**Comment by ixhal** [comment]
Yep I agree that is a lot of time for washing, Will look into this more when I go through and do the economy balancing and include this in there

**Comment by ixhal** [comment]
Going to close this now since we made some changes to it!
Thanks for the feedback
