### ISSUE TITLE
[BUG] MDT

### ISSUE THREAD

**Issue by HoneySouffles** [Reprieve-RP/feedback#80]
When you are on shift for the day, EMS or PD, and you clock out for the night but decide to stick around the city and hang out you are still marked active duty on the MDT. With this you can be tracked with your waypoint from the MDT. You wont appear on the services app or have your blip appear on the map for others to see, just appearing on the MDT. Once you leave the city you are off the MDT.

**Comment by ixhal** [comment]
Issue should be fixed on the next restart! Thanks! :)
