### ISSUE TITLE
Placing in vehicles

### ISSUE THREAD

**Issue by JakeWalker1** [Reprieve-RP/feedback#81]
**What is the issue involving?**
You cant place people in a 2 seated car

**In your opinion what is the way to fix this?**
Make it so we can so we don't have to escort people while driving them to the hospital if no meds are around

**Additional information**

**Comment by ixhal** [comment]
TBH the entire system for escorting aswell as placing people into vehicles probably needs to be recoded as it currently sucks 🤣 Will look into this as soon as I have more time and less bugs 👀
