### ISSUE TITLE
[ENHANCEMENT] MEDIC REVIVE

### ISSUE THREAD

**Issue by HoneySouffles** [Reprieve-RP/feedback#83]
**What feature you want to improve**
Medic Revive

**How could this feature be improved? Please describe your idea as much as possible**
When a medic revives the animation only rolls for a couple seconds and then you stand there awkwardly. Maybe increase the duration of the animation to the entire length it takes to revive so ppl are aware we are in the process of revive, so it doesnt look like we are standing around.

**Comment by ixhal** [comment]
Issue is now fixed, Thanks for the report! :)
